/**
 * VALIDATION UTILITY: Structural & Confidence Audit
 * * EXPECTATIONS:
 * - Input: Matches JSON files in 'data/output' generated by 'src/index.ts'.
 * - Confidence Threshold: Scores > 0.90 are considered stable; < 0.80 indicate potential OCR failure.
 * - Structure: Identifies 'blocks' which should map to physical columns or paragraphs in the dictionary.
 * * EXECUTION:
 * - Run via 'npx tsx src/validate.ts'.
 * - Output: A per-file terminal report summarizing internal metadata without opening the massive JSON files.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

// Resolved path to the directory containing the OCR results to be audited.
const OUTPUT_DIR = path.join(process.cwd(), 'data', 'output');

/**
 * Iterates through the hierarchical JSON structure to extract quality metrics.
 * @param fileName - The name of the JSON file to be analyzed.
 */
const auditJsonFile = (fileName: string): void => {
  const filePath = path.join(OUTPUT_DIR, fileName);
  const rawData = fs.readFileSync(filePath, 'utf-8');
  const json = JSON.parse(rawData);

  // fullTextAnnotation is the root object; if missing, the OCR process failed to find any text.
  const annotation = json.fullTextAnnotation;
  if (!annotation) {
    console.log(`[!] CRITICAL: ${fileName} contains no text data.`);
    return;
  }

  let wordCount = 0;
  let cumulativeConfidence = 0;
  let flaggedWordCount = 0;

  // Google structures data as Page > Block > Paragraph > Word.
  // We drill down to the Word level to check individual accuracy scores.
  annotation.pages.forEach((page: any) => {
    page.blocks.forEach((block: any) => {
      block.paragraphs.forEach((para: any) => {
        para.words.forEach((word: any) => {
          wordCount++;
          // 'confidence' is a float from 0 to 1 representing Google's certainty of the character.
          const score = word.confidence || 0;
          cumulativeConfidence += score;
          
          // 0.80 is the floor for reliable translation data; below this, diacritics may be wrong.
          if (score < 0.8) {
            flaggedWordCount++;
          }
        });
      });
    });
  });

  // Math: Calculate average to see if the overall page quality is fit for LLM processing.
  const averageConfidence = (cumulativeConfidence / wordCount).toFixed(4);
  
  // Logical Check: 'blocks' usually represent the physical layout (e.g., 2 columns = 2 blocks).
  // If this number is 1, the OCR merged the columns, which will break Farsi/English pairing.
  const blockCount = annotation.pages[0].blocks.length;

  console.log(`FILE AUDIT: ${fileName}`);
  console.log(`- Avg Confidence: ${averageConfidence}`);
  console.log(`- Flagged Words: ${flaggedWordCount} (Under 0.80)`);
  console.log(`- Layout Blocks: ${blockCount}`);
  // Previewing the text allows for a manual "sanity check" of character encoding.
  console.log(`- Content Sample: ${annotation.text.substring(0, 80).replace(/\n/g, ' ')}...`);
  console.log('---');
};

/**
 * Orchestrates the audit of all files in the output directory.
 */
const main = (): void => {
  // Mechanical check for the existence of the output folder.
  if (!fs.existsSync(OUTPUT_DIR)) {
    console.error('Failure: The "data/output" directory does not exist.');
    return;
  }

  const jsonFiles = fs.readdirSync(OUTPUT_DIR).filter(f => f.endsWith('.json'));

  if (jsonFiles.length === 0) {
    console.warn('Empty: No JSON files found to validate.');
    return;
  }

  // Processes each file sequentially for terminal clarity.
  jsonFiles.forEach(auditJsonFile);
};

main();